Grip command
P8P-7/core pull request #26
Opened 2018-06-22 08:04 UTC by aranna00

Arm move command
Failed IK test
Arm movement test

2018-06-22 10:22 UTC, ObeA requested changes

2018-06-22 10:22 UTC, ObeA commented on src/controller/include/goliath/controller/commands/move_arm_command.h
> +                                 const proto::commands::ServoCommand &servoCommand);
Iets te letterlijk gekopieerd denk ik.

2018-06-22 10:22 UTC, ObeA commented on src/controller/include/goliath/controller/commands/grip_command.h
> +                                 const proto::commands::ServoCommand &servoCommand);
Idem

2018-06-22 10:22 UTC, ObeA commented on src/controller/include/goliath/controller/commands/move_arm_command.h
> +        void executeServoCommand(std::shared_ptr<handles::ServoHandle> servoHandle,
Wordt niet geimplementeerd.

2018-06-22 10:22 UTC, ObeA commented on tests/test_arm_ik.cpp
> +#define BOOST_TEST_MODULE test_arm_ik
Mag wel weg.

2018-06-22 10:22 UTC, ObeA commented on tests/test_arm_prepos.cpp
> +#define BOOST_TEST_MODULE test_arm_ik
Idem

2018-06-22 10:29 UTC, kleisauke requested changes

2018-06-22 10:29 UTC, kleisauke commented on src/controller/src/commands/grip_command.cpp
> +    }
```cpp
servoGripper->setGoalPosition(gripCommand.gripping() ? 735 : 447)
```

2018-06-22 10:29 UTC, kleisauke commented on src/modules/servo/src/servo_handle.cpp
>      device->setDirectionCallback(std::move(txCallback));
Master needs to be merged in this PR, for e.g. this call is already gone.

2018-06-24 14:21 UTC, janwilts approved these changes
Inmiddels OK

2018-06-24 17:39 UTC, kleisauke approved these changes

2018-07-05 20:34 UTC, closed without merging